[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Python_Functions"
version = "1.0.1"
authors = [
    { name="Dragmine149" }
]
description = "A list of functions ready to install and use."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/FunAndHelpfulDragon/python-Functions/"
"Bug Tracker" = "https://github.com/FunAndHelpfulDragon/python-Functions/issues"