from . import PythonFunctions as PythonFunctions
from _typeshed import Incomplete

TD: Incomplete
dsp: Incomplete

def callback(value): ...
def test_set() -> None: ...
def test_add() -> None: ...
def test_Remove() -> None: ...
