from . import template as template
from _typeshed import Incomplete

disabled: bool

class save(template.SaveTemplate):
    SCOPES: Incomplete
    service: Incomplete
    pageSize: int
    def __init__(self) -> None: ...
    def credentials(self, data) -> None: ...
    def WriteData(self, data: any, path: str, Encoding: bool = ...) -> bool: ...
    def ReadData(self, path: str, Encoding: bool = ...) -> any: ...
    def MakeFolders(self, path: str): ...
    def DeleteFolder(self, path: str): ...
    def DeleteFile(self, path: str): ...

def load(): ...
