from . import template as template

class Save(template.SaveTemplate):
    def WriteData(self, data: any, path: str, Encoding: bool = ...) -> bool: ...
    def ReadData(self, path: str, Encoding: bool = ...) -> any: ...
    def MakeFolders(self, path: str): ...
    def DeleteFile(self, path: str): ...
    def DeleteFolder(self, path: str): ...

def load(): ...
