from _typeshed import Incomplete

class SaveTemplate:
    parent: Incomplete
    tempFile: Incomplete
    data: Incomplete
    def __init__(self) -> None: ...
    def credentials(self, data) -> None: ...
    def WriteData(self, data: any, path: str, Encoding: bool = ...) -> bool: ...
    def ReadData(self, path: str, Encoding: bool = ...) -> any: ...
    def MakeFolders(self, path: str): ...
    def DeleteFile(self, path: str): ...
    def DeleteFolder(self, path: str): ...

def load(): ...
