from _typeshed import Incomplete

from . import PythonFunctions as PythonFunctions

Check: Incomplete

def int_check(chk: Check): ...
def yn_check(chk: Check, vIn: str): ...

chk: Incomplete

def test_int() -> None: ...
def test_yes() -> None: ...
def test_no() -> None: ...
def test_error() -> None: ...
