from . import PythonFunctions as PythonFunctions
from _typeshed import Incomplete

Check: Incomplete
chk: Incomplete

def int_check(): ...
def yn_check(vIn: str): ...
def test_int() -> None: ...
def test_yes() -> None: ...
def test_no() -> None: ...
def test_error() -> None: ...
