from _typeshed import Incomplete

from . import PythonFunctions as PythonFunctions

Encryption: Incomplete
enc: Incomplete
gblKey: Incomplete

def test_Key() -> None: ...
def test_Encrypt() -> None: ...
def test_Decrypt_wrong() -> None: ...
def test_Decrypt_Correct() -> None: ...
def test_finish() -> None: ...
