from . import PythonFunctions as PythonFunctions
from _typeshed import Incomplete

IsDigit: Incomplete

def test_isdigit() -> None: ...
def test_isdigit_str() -> None: ...
def test_notDigit() -> None: ...
