from . import PythonFunctions as PythonFunctions
from _typeshed import Incomplete

run: Incomplete
IsDigit: Incomplete

def test_mark() -> None: ...
def test_get_mark() -> None: ...
def test_compare() -> None: ...
