from . import PythonFunctions as PythonFunctions
from _typeshed import Incomplete

Save: Incomplete
sv: Incomplete
csvData: Incomplete

def test_MakeFolder() -> None: ...
def test_MakeFolders() -> None: ...
def test_write_Data_None() -> None: ...
def test_write_Data_JSON() -> None: ...
def test_write_Data_BINARY() -> None: ...
def test_Write_Data_Crypto() -> None: ...
def test_Save_Data_CSV() -> None: ...
def test_Read_Data_None() -> None: ...
def test_Read_Data_JSON() -> None: ...
def test_Read_Data_BINARY() -> None: ...
def test_Read_Data_Crypto() -> None: ...
def test_Read_Data_CSV() -> None: ...
def test_Remove_File_None() -> None: ...
def test_Remove_File_JSON() -> None: ...
def test_Remove_File_BINARY() -> None: ...
def test_Remove_File_Crypto() -> None: ...
def test_Remove_Folder() -> None: ...
def test_Finish() -> None: ...
