from _typeshed import Incomplete

from . import PythonFunctions as PythonFunctions

TD: Incomplete
dsp: Incomplete

def callback(value): ...
def test_set() -> None: ...
def test_add() -> None: ...
def test_List() -> None: ...
def test_Remove() -> None: ...
