import typing

class Clean:
    def GetData(self, path: str) -> typing.List: ...
    def RemoveHidden(self, data: typing.List[str]) -> typing.List[str]: ...
    def RemoveReserved(self, data: typing.List[str], reserved: typing.List[str]) -> typing.List[str]: ...
    def clean(self, path: str, reserved: typing.List[str] = ...) -> typing.List[str]: ...
