from _typeshed import Incomplete

def ConsoleFormat(): ...

class Print:
    msg: Incomplete
    colour: Incomplete
    options: Incomplete
    def __init__(self, msg, colour: Incomplete | None = ..., options: Incomplete | None = ...) -> None: ...
    def GetValue(self): ...

class reverse:
    code: Incomplete
    def __init__(self, code) -> None: ...
    def reverse(self): ...

def c(choice: Incomplete | None = ...): ...

class colourRetrieve:
    fullName: Incomplete
    colourCode: Incomplete
    def __init__(self, choice: Incomplete | None = ...) -> None: ...
