from _typeshed import Incomplete

start: Incomplete
markers: Incomplete

def Mark() -> int: ...
def GetMarkTime(i: int) -> float: ...
def CompareIndex(a: int, b: int) -> float: ...
def End() -> float: ...
