import typing
from . import Colours as Colours
from .Check import Check as Check
from .Message import Message as Message
from _typeshed import Incomplete

canRead: bool

class Display:
    options: Incomplete
    gridData: Incomplete
    chk: Incomplete
    cursorPosition: Incomplete
    def __init__(self) -> None: ...
    def SetOptions(self, options: typing.Dict): ...
    def AddOption(self, option: typing.Tuple, *, index: int = ...): ...
    def RemoveOption(self, index: int): ...
    def RemoveOptions(self, *index: int): ...
    def RemoveAllOptions(self) -> None: ...
    def ShowHeader(self, *, text: str = ..., typewriter: bool = ..., pace: int = ...): ...
    def ShowOptions(self, *, useList: bool = ...): ...
