import tkinter as tk
from _typeshed import Incomplete

class ui:
    canvas: Incomplete
    Elements: Incomplete
    Frames: Incomplete
    callback: Incomplete
    font: Incomplete
    def __init__(self, title: str = ..., callback: Incomplete | None = ...) -> None: ...
    def FontSettings(self, *, font: str = ..., size: int = ...) -> None: ...
    def CreateFrame(self, row: int = ..., column: int = ...) -> tk.Frame: ...
    def AddButton(self, text: str = ..., callback: Incomplete | None = ..., row: int = ..., column: int = ..., *, textVar: tk.StringVar = ..., frame: Incomplete | None = ..., sticky: str = ..., callbackArgs: bool = ..., rowspan: int = ..., columnspan: int = ...) -> tk.Button: ...
    def AddLabel(self, text: str = ..., row: int = ..., column: int = ..., *, textVar: tk.StringVar = ..., frame: Incomplete | None = ..., sticky: str = ..., rowspan: int = ..., columnspan: int = ..., image: tk.PhotoImage = ...) -> tk.Label: ...
    def AddTexBox(self, textVar: tk.StringVar, row: int = ..., column: int = ..., *, frame: tk.Frame = ..., sticky: str = ..., rowspan: int = ..., columnspan: int = ..., show: str = ...) -> tk.Entry: ...
    def ChangeState(self, Element: dict, state: bool = ...): ...
    def CreateStringVar(self, frame: tk.Frame = ..., default: str = ...) -> tk.StringVar: ...
