name: Build python package

on: push

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build --outdir dist/latest
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Latest Build
          path: dist/latest
      - name: Install documentation dependencies
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
      - name: Build Documentation
        run: |
          rm -rf docs/build
          cd docs
          make html
      - name: Upload Documentatioon Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Latest Docs
          path: docs/build/html
